server:
  port: 8088  #端口号
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curriculum?serverTimezone=UTC&useSSL=false  #数据库url
    driver-class-name: com.mysql.jdbc.Driver   #数据库驱动
    username: root
    password: 123456
  application:
    name: admin #设置项目名称

  servlet:
    multipart:
      max-file-size: 10MB  #上传文件最大大小
      max-request-size: 10MB #客户端能发送请求的最大大小
ip: localhost
