server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curriculum?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
    name: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB